import { WorkClient } from '@/components/WorkClient';
import { Project } from '@/types';

// Placeholder data - will be replaced by Sanity CMS data
const placeholderProjects: Project[] = [
  {
    _id: '1',
    title: 'Projet Alpha',
    slug: 'projet-alpha',
    category: 'motion',
    year: '2024',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: true,
    order: 1,
  },
  {
    _id: '2',
    title: 'Gravure Série Noire',
    slug: 'gravure-serie-noire',
    category: 'print',
    year: '2024',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: true,
    order: 2,
  },
  {
    _id: '3',
    title: 'Identité Maison Blanche',
    slug: 'identite-maison-blanche',
    category: 'identite',
    year: '2024',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 3,
  },
  {
    _id: '4',
    title: 'Motion Reel 2024',
    slug: 'motion-reel-2024',
    category: 'motion',
    year: '2024',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: true,
    order: 4,
  },
  {
    _id: '5',
    title: 'Expérimentation 01',
    slug: 'experimentation-01',
    category: 'bac-a-sable',
    year: '2023',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 5,
  },
  {
    _id: '6',
    title: 'Campagne Luxe',
    slug: 'campagne-luxe',
    category: 'motion',
    year: '2023',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: true,
    order: 6,
  },
  {
    _id: '7',
    title: 'Affiche Festival',
    slug: 'affiche-festival',
    category: 'print',
    year: '2023',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 7,
  },
  {
    _id: '8',
    title: 'Brand Identity Studio',
    slug: 'brand-identity-studio',
    category: 'identite',
    year: '2023',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 8,
  },
  {
    _id: '9',
    title: 'Recherches Visuelles',
    slug: 'recherches-visuelles',
    category: 'bac-a-sable',
    year: '2023',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 9,
  },
  {
    _id: '10',
    title: 'Animation Product',
    slug: 'animation-product',
    category: 'motion',
    year: '2022',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 10,
  },
  {
    _id: '11',
    title: 'Estampes Japonaises',
    slug: 'estampes-japonaises',
    category: 'print',
    year: '2022',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 11,
  },
  {
    _id: '12',
    title: 'Tests Typographiques',
    slug: 'tests-typographiques',
    category: 'bac-a-sable',
    year: '2022',
    thumbnail: { _type: 'image', asset: { _ref: '', _type: 'reference' } },
    images: [],
    featured: false,
    order: 12,
  },
];

export const metadata = {
  title: 'Work — Timoléon Sauvillers',
  description: 'Projets de motion design, gravure, identité visuelle et expérimentations.',
};

export default function WorkPage() {
  // TODO: Fetch all projects from Sanity
  // const projects = await getAllProjects();
  
  return <WorkClient projects={placeholderProjects} />;
}
